/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'tarke' at '12/14/16 1:39 PM' with Gradle 3.0
 *
 * @author tarke, @date 12/14/16 1:39 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
